package:
    name: ccpi-preprocessing
    version: {{ environ['CIL_VERSION'] }}
    
build:
    preserve_egg_dir: False
    script_env:
      - CIL_VERSION 
requirements:
    build:
        - python
        - numpy
        - scipy
        - matplotlib
        - cython
        - pytz
        - certifi
    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - pytz
        - certifi
        
about:
    home: http://www.ccpi.ac.uk
    summary: 'CCPi Core Imaging Library (Preprocessing)'
